import 'dart:math';

import '../../domain/models/document_model.dart';
import '../../domain/services/data_service.dart';

/// Mock document service with three sample documents.
///
/// Simulates realistic network latency with random jitter:
/// - Load: 600–1500 ms (first load slower at 1200–2500 ms to simulate cold start)
/// - Save: 800–2000 ms
/// - Second save always fails (simulates server-side conflict).
class MockDataService implements DataService {
  int _saveCallCount = 0;
  int _loadCallCount = 0;
  final _rng = Random();

  static const String _projectId = 'proj-001';

  static final Map<String, DocumentModel> _documents = {
    'doc-001': DocumentModel(
      id: 'doc-001',
      name: 'analysis-report.md',
      projectId: _projectId,
      mimeType: 'text/markdown',
      content: _analysisReportContent,
    ),
    'doc-002': DocumentModel(
      id: 'doc-002',
      name: 'notes.txt',
      projectId: _projectId,
      mimeType: 'text/plain',
      content: _notesContent,
    ),
    'doc-003': DocumentModel(
      id: 'doc-003',
      name: 'pipeline-config.md',
      projectId: _projectId,
      mimeType: 'text/markdown',
      content: _pipelineConfigContent,
    ),
  };

  @override
  List<String> get availableDocumentIds => _documents.keys.toList();

  /// Random delay in [minMs, maxMs] range to simulate network jitter.
  Future<void> _jitteredDelay(int minMs, int maxMs) async {
    final ms = minMs + _rng.nextInt(maxMs - minMs + 1);
    await Future.delayed(Duration(milliseconds: ms));
  }

  @override
  Future<DocumentModel> loadDocument(String fileId, String projectId) async {
    _loadCallCount++;
    // First load is slower (cold start). Subsequent loads are faster (warm cache).
    if (_loadCallCount == 1) {
      await _jitteredDelay(1200, 2500);
    } else {
      await _jitteredDelay(600, 1500);
    }

    final doc = _documents[fileId];
    if (doc == null) {
      throw Exception('Document not found: $fileId');
    }
    return doc;
  }

  @override
  Future<bool> saveDocument(String fileId, String content) async {
    await _jitteredDelay(800, 2000);

    _saveCallCount++;

    // Simulate one failure on the second save attempt.
    if (_saveCallCount == 2) {
      return false;
    }

    // Update the stored document content.
    final doc = _documents[fileId];
    if (doc != null) {
      _documents[fileId] = doc.copyWith(content: content);
    }
    return true;
  }

  // ── Mock document content ──────────────────────────────────────────────────

  static const String _analysisReportContent = '''# Analysis Report

This report summarises the flow cytometry analysis performed on the **immunophenotyping** dataset using the Tercen platform.

---

## Overview

The analysis pipeline processes *high-dimensional* flow cytometry data to identify and characterise immune cell populations. Key steps include compensation, gating, clustering, and visualisation.

> This analysis was generated by the Tercen LLM assistant based on the uploaded FCS files and the selected workflow template.

## Marker Panel

| Marker | Channel | Purpose | Clone |
|--------|---------|---------|-------|
| CD3 | FITC | T-cell lineage | OKT3 |
| CD4 | PE | Helper T-cells | RPA-T4 |
| CD8 | APC | Cytotoxic T-cells | SK1 |
| CD19 | PE-Cy7 | B-cell lineage | HIB19 |
| CD45 | BV421 | Pan-leukocyte | HI30 |

## Results

The clustering algorithm identified **12 distinct populations** across all samples. The major populations are:

1. CD3+ T-cells (45.2%)
2. CD19+ B-cells (12.8%)
3. CD3-CD19- NK cells (8.4%)
4. Monocytes (15.1%)
5. Remaining populations (18.5%)

### Key Findings

- The **CD4/CD8 ratio** was within normal range (1.5-2.5) for all healthy controls
- ~~Previous analysis suggested an elevated CD19 count~~ -- this was corrected after re-gating
- Sample processing used `flowCore::read.FCS()` for file import

### Scatter Plot

![Population scatter plot](https://tercen.example/api/v1/files/img-scatter-001.png)

### Code Used

```r
library(flowCore)
library(FlowSOM)

# Read FCS files
fs <- read.flowSet(files)

# Compensate
fs_comp <- compensate(fs, comp_matrix)

# Cluster with FlowSOM
som <- FlowSOM(fs_comp, colsToUse = markers)
```

---

## Conclusion

The immunophenotyping analysis confirms expected population distributions. For detailed per-sample breakdowns, see the [Data Viewer results](https://tercen.example/project/proj-001/data/results-001).

*Report generated on 2026-03-15 by Tercen LLM Assistant*
''';

  static const String _notesContent =
      '''Meeting Notes - Flow Cytometry Project Review

Date: March 15, 2026
Attendees: Dr. Smith, Dr. Garcia, Martin (Bioinformatics)

Summary of Discussion:

The team reviewed the current state of the immunophenotyping analysis pipeline. Dr. Smith presented the initial results from the first batch of 24 samples processed through the automated workflow.

Key points discussed:

The compensation matrix needs to be recalculated using single-stain controls from the March batch. The current matrix was derived from February controls and shows slight spillover in the PE-Cy7 channel.

Dr. Garcia suggested implementing a two-stage gating strategy: first gate on viable singlets using FSC/SSC, then apply the FlowSOM clustering on the cleaned population. This approach reduces noise from debris and doublets.

Martin confirmed that the Tercen workflow can be modified to include the additional preprocessing step. The estimated processing time per sample would increase from 2 minutes to approximately 3 minutes.

Action items:

Run single-stain controls on the March samples by end of week.
Update the compensation matrix in the Tercen workflow configuration.
Add the two-stage gating step to the pipeline before clustering.
Re-run the first 24 samples with the updated pipeline for comparison.
Schedule follow-up review for next Thursday at 2pm.

The team agreed that once the pipeline is validated with the updated settings, it will be applied to the full cohort of 180 samples. Expected completion: end of March 2026.

Additional notes from Martin:

The current Tercen project is set up with three workflows: preprocessing, clustering, and visualisation. Each can be run independently or chained together. The LLM assistant has been configured to generate reports automatically after each workflow completion.

File storage is within the Tercen project under the reports folder. All generated documents are versioned and can be viewed through the Document Editor or downloaded as markdown files.
''';

  static const String _pipelineConfigContent =
      '''# Pipeline Configuration

This document describes the configuration for the immunophenotyping analysis pipeline.

## Setup Instructions

1. Create a new Tercen project and upload FCS files
2. Import the workflow template from the shared library
3. Configure the compensation matrix (see below)
4. Set the clustering parameters
5. Run the pipeline and review results

## Compensation Matrix

```yaml
compensation:
  method: "spillover"
  source: "single-stain-controls"
  channels:
    - FITC
    - PE
    - APC
    - PE-Cy7
    - BV421
  auto_calculate: true
```

## Clustering Parameters

```json
{
  "algorithm": "FlowSOM",
  "parameters": {
    "xdim": 10,
    "ydim": 10,
    "nClusters": 15,
    "maxMeta": 20,
    "seed": 42
  },
  "markers": ["CD3", "CD4", "CD8", "CD19", "CD45"],
  "transform": "arcsinh",
  "cofactor": 150
}
```

## Parameter Reference

| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| xdim | integer | 10 | SOM grid X dimension |
| ydim | integer | 10 | SOM grid Y dimension |
| nClusters | integer | 15 | Target number of metaclusters |
| maxMeta | integer | 20 | Maximum metaclusters |
| seed | integer | 42 | Random seed for reproducibility |
| transform | string | arcsinh | Data transformation method |
| cofactor | number | 150 | Arcsinh cofactor |

## Quality Control Script

```r
# QC check after clustering
library(FlowSOM)

qc_results <- list()
for (cluster_id in seq_len(nClusters)) {
  cells <- GetClusters(som) == cluster_id
  qc_results[[cluster_id]] <- list(
    count = sum(cells),
    percentage = mean(cells) * 100,
    median_markers = apply(data[cells, markers], 2, median)
  )
}

# Flag clusters with fewer than 100 cells
small_clusters <- which(sapply(qc_results, function(x) x\${''}count < 100))
message(sprintf("Warning: %d clusters have fewer than 100 cells", length(small_clusters)))
```

## Output Files

The pipeline generates the following output files:

1. **results.csv** -- per-cell cluster assignments
2. **summary.md** -- population statistics report
3. **scatter_plots/** -- PNG visualisations per marker pair
4. **qc_report.md** -- quality control metrics
''';
}
